- lib/gitsh/environment.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/history.rb
- lib/gitsh/interactive_runner.rb
- lib/gitsh/magic_variables.rb
- lib/gitsh/parser.rb
- lib/gitsh/prompter.rb
- lib/gitsh/transformer.rb
- spec/units/environment_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/magic_variables_spec.rb
- spec/units/prompter_spec.rb
This PR paves the way for making unset variables raise an error (#136) which in turn will pave the way for lazily evaluating variables in command arguments (#197).
After attempting to implement lazy variable evaluation directly it became apparent that staying consistent with the way general purpose Unix shells handle unset variables is going to introduce a lot of complexity, far more than keeping that behaviour would justify (@mike-burns never liked it anyway—see discussion on #136—and I probably should have listened).
* Modify `Gitsh::Environment#fetch` and `Gitsh::GitRepository#config` to raise if no default value is given.
* Move default values from arguments to blocks to easily distinguish between “there is no default” and “the default is set to `nil`”.
* Remove …
> Eliminate nils

- lib/gitsh/environment.rb
- lib/gitsh/error.rb
- lib/gitsh/interpreter.rb
- lib/gitsh/transformer.rb
- man/man1/gitsh.1
- spec/integration/variables_spec.rb
- spec/units/environment_spec.rb
- spec/units/interpreter_spec.rb
- spec/units/transformer_spec.rb
If a command uses a variable that has not previously been set, the command will not be executed, and an error message will be printed identifying the unset variable.
Fixes #136
> Consider unset variables to be an error.

- lib/gitsh/argument_builder.rb
- lib/gitsh/argument_list.rb
- lib/gitsh/arguments/composite_argument.rb
- lib/gitsh/arguments/string_argument.rb
- lib/gitsh/arguments/variable_argument.rb
- lib/gitsh/commands/git_command.rb
- lib/gitsh/commands/internal_command.rb
- lib/gitsh/commands/shell_command.rb
- lib/gitsh/transformer.rb
- spec/integration/chaining_spec.rb
- spec/support/arguments.rb
- spec/units/argument_builder_spec.rb
- spec/units/argument_list_spec.rb
- spec/units/arguments/composite_argument_spec.rb
- spec/units/arguments/string_argument_spec.rb
- spec/units/arguments/variable_argument_spec.rb
- spec/units/commands/git_command_spec.rb
- spec/units/commands/internal/chdir_spec.rb
- spec/units/commands/internal/echo_spec.rb
- spec/units/commands/internal/exit_spec.rb
- spec/units/commands/internal/help_spec.rb
- spec/units/commands/internal/set_spec.rb
- spec/units/commands/internal/unknown_spec.rb
- spec/units/commands/internal_command_spec.rb
- spec/units/commands/shell_command_spec.rb
- spec/units/transformer_spec.rb
Originally, gitsh would replace a variable with its value when transforming a command's AST into a command object. This made it impossible to write and then read a variable in the same command, e.g. with `:set x 1 && :echo $x`
Fixes #197
> Lazily evaluate variables

- lib/gitsh/prompter.rb
- man/man1/gitsh.1
- spec/integration/prompt_spec.rb
- spec/units/prompter_spec.rb
By default, only show the first 15 characters of the branch name in the prompt.
Fixes #143
> Abbreviate branch name

- lib/gitsh/commands/error_handler.rb
- lib/gitsh/commands/factory.rb
- lib/gitsh/interpreter.rb
- lib/gitsh/transformer.rb
- spec/integration/chaining_spec.rb
- spec/units/commands/error_handler_spec.rb
- spec/units/commands/factory_spec.rb
- spec/units/interpreter_spec.rb
- spec/units/transformer_spec.rb
This PR moves the error handling from the `Gitsh::Interpreter` to a `Gitsh::Commands::ErrorHandler` decorator, so that a line that contains multiple commands can continue, even if one of those commands fails.
It makes it possible to do things like this:
```
% :set b "This is B"
% :echo $a || :echo $b
This is B
```
Fixes #213
> Command error handling

- CONTRIBUTING.md
- Makefile.am
- configure.ac
The way we were building the `INSTALL` instructions was causing `make distcheck` to fail: `make clean` wasn't cleaning up the `INSTALL` file, which was what we wanted for building in the source directory, but not when building from another directory.
Letting autoconf handle the `INSTALL` file fixes this problem, and simplifies the Makefile in the process.
> Update INSTALL in the configure script.

- lib/gitsh/cli.rb
- lib/gitsh/commands/internal_command.rb
- lib/gitsh/error.rb
- lib/gitsh/script_runner.rb
- man/man1/gitsh.1
- spec/integration/source_command_spec.rb
- spec/units/cli_spec.rb
- spec/units/commands/internal/source_spec.rb
- spec/units/commands/internal_command_spec.rb
- spec/units/script_runner_spec.rb
`:source path` will run any Git and gitsh commands in the file at `path`. It can modify the environment of the gitsh session it's called from, much like the `source` command in Unix shells.
> :source command

- lib/gitsh/interactive_runner.rb
- lib/gitsh/terminal.rb
- spec/units/interactive_runner_spec.rb
- spec/units/terminal_spec.rb
When gitsh receives a `SIGWINCH`, it informs Readline of the new terminal size.
Previously, the new terminal size was determined using the `tput cols` and `tput lines` commands. However, when Readline is sent the terminal size it sets `COLUMNS` and `LINES` environment variables, and if these environment variables are set `tput` will read them instead of actually checking the terminal size. This means that we were never actually passing the new terminal size to Readline, we were just passing whatever size we had when the environment variables were set, over and over again.
Determining the terminal size by trying each of the following in turn seems to work better:
1. `stty size` – this might fail, because some implementations of `stty` don't support `size`, e.g. on Solaris.
2. `env …
> Fix window size bugs

- lib/gitsh/commands/git_command.rb
- lib/gitsh/commands/shell_command.rb
- lib/gitsh/shell_command_runner.rb
- spec/units/commands/git_command_spec.rb
- spec/units/commands/shell_command_spec.rb
- spec/units/shell_command_runner_spec.rb
Refactors `Gitsh::Commands::ShellCommand` and `Gitsh::Commands::GitCommand`
* Extract a `Gitsh::ShellCommandRunner` from `Gitsh::Commands::ShellCommand`.
* Replace inheritance with composition.
* Pave the way to solve #134 without modifying the behaviour of Git commands.
> Refactor shell commands

- lib/gitsh/commands/internal_command.rb
- spec/integration/source_command_spec.rb
The `:cd` command already supported `~` in paths, but `:source` did not. This commit fixes that inconsistency.
> Support ~ in paths given to `:source`

- src/gitsh.rb.in
In which I correct an embarrassing oversight.
Fixes #233
> Use non-zero exit status on fatal errors.

- lib/gitsh/magic_variables.rb
- spec/integration/magic_variables_spec.rb
- spec/units/magic_variables_spec.rb
The magic variables that gitsh provides all depend on certain state, e.g. the `$_merge_base` variable is only applicable during a merge.
This commit brings magic variables into line with regular user-defined variables, but raising an `UnsetVariableError` if they aren't currently set, i.e. if the state from which the variable derives its value doesn't exist.
Fixes #230
> Raise UnsetVariableError for magic variables.

- vendor/vendorize
The vendorize script assumed that the correct require path for any given gem was "lib", and only "lib". While this assumption holds true for all of the gems we currently depend on, removing it will make it easier to add future dependencies without potentially obscure bugs.
Fixes #203
> More correct vendorize script.

- README.md
We've made the intro video on Upcase free to all users (no subscription required), so I'd like to add a link to the video from the README.
Happy to revise the text if something else makes more sense.
> Add link to video on Upcase

- spec/Makefile.am
On Mac OS X 10.11.4 and Debian 8 using system Ruby the `make check` task
would fail on the `units/terminal_spec.rb` file with a `NoMethodError`
for `allow` on `CommandStubber`. This was probably because rspec-mocks
did not properly laod.
Running specs using `bundle exec rspec` solves this.
> Use bundle exec rspec to run specs

- lib/gitsh/line_editor_history_filter.rb
- spec/support/gitsh_runner.rb
- spec/units/line_editor_history_filter_spec.rb
This class was defined in the gith directory, but not nested under the Gitsh module.
(Very simple PR, will merge without review if CI passes)
> Move LineEditorHistoryFilter into Gitsh.

- lib/gitsh/cli.rb
- lib/gitsh/exit_statuses.rb
- spec/integration/default_git_path_spec.rb
- spec/integration/running_scripts_spec.rb
- spec/support/fixtures.rb
- spec/units/cli_spec.rb
Display a helpful message and exit early when gitsh is installed on a
system without git or when a non-existent git is specified using the
`--git` option.
This fixes #193.
> Provide a helpful message if git is not executable

- lib/gitsh/completer.rb
- lib/gitsh/completion_escaper.rb
- lib/gitsh/interactive_runner.rb
- spec/support/file_system.rb
- spec/units/completer_spec.rb
- spec/units/completion_escaper_spec.rb
- spec/units/interactive_runner_spec.rb
We'd set `Gitsh::LineEditor.completion_append_character` to `nil`, and then append a space to any completion option that wasn't a directory path (e.g., completions might include `"file.txt "` with a trailing space, and `"dir/"` without a trailing space).
The benefit of this was that you could tab complete a directory name, not have a space appended, and continue typing the path. You could also tab complete any other argument, have a space appended, and begin typing the next argument.
The down side was that we needed to manually remove the space from the end of the options if we were completing a quoted argument, and we needed to avoid escaping spaces at the end of a completion when completing an unquoted argument.
We set `LineEditor.completion_append_character` dynamically based on the …
> Refactor completion suffix

- ext/gitsh/extconf.rb
- ext/gitsh/src/line_editor.c
- lib/gitsh/completer.rb
- lib/gitsh/completion_escaper.rb
- lib/gitsh/interactive_runner.rb
- lib/gitsh/parser.rb
- lib/gitsh/parser/character_class.rb
- lib/gitsh/quote_detector.rb
- man/man1/gitsh.1
- spec/integration/tab_completion_spec.rb
- spec/support/file_system.rb
- spec/units/completer_spec.rb
- spec/units/completion_escaper_spec.rb
- spec/units/interactive_runner_spec.rb
- spec/units/line_editor_spec.rb
- spec/units/parser/character_class_spec.rb
- spec/units/parser_spec.rb
- spec/units/quote_detector_spec.rb
Allows users to tab-complete options that contain exotic characters like spaces, by:
* Explicitly telling GNU Readline which characters constitute word boundaries in the gitsh language.
* Using GNU Readline's `char_is_quoted_p` setting to inform Readline when a word boundary is escaped.
* Expanding the parser to support more escape sequences.
* Decorating the completer with a new `Gitsh::CompletionEscaper` which unescapes user input on the way in (so we can match it against the possibly completions) and then escapes the completions on the way out (so they can be correctly parsed by the shell)
> Tab complete spaces (and other special characters)

- ext/gitsh/extconf.rb
- ext/gitsh/src/line_editor.c
- lib/gitsh/completer.rb
- spec/integration/tab_completion_spec.rb
- spec/units/completer_spec.rb
- spec/units/line_editor_spec.rb
When the thing we've managed to complete isn't a full argument (i.e. it's a directory name, and the user may want to add more components to the path), don't append a quote if it's a quoted argument.
Fixes #262
> Don't always close quotes when tab completing.

- lib/gitsh/environment.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/git_repository/status.rb
- lib/gitsh/prompt_color.rb
- lib/gitsh/prompter.rb
- spec/integration/prompt_spec.rb
- spec/units/environment_spec.rb
- spec/units/git_repository/status_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/interactive_runner_spec.rb
- spec/units/prompt_color_spec.rb
- spec/units/prompter_spec.rb
Generating and displaying the prompt in gitsh is currently painfully slow on my MacBook Air. This PR is an attempt to improve on this.
I started to investigate by printing all git commands passed to `Open3.capture3` in `GitRepository#git_output`:
```
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git symbolic-ref HEAD --short"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git symbolic-ref HEAD --short"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git symbolic-ref HEAD --short"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git rev-parse --git-dir"
"/usr/bin/env git status --porcelain"
"/usr/bin/env git status --porcelain"
"/usr/bin/env git config …
```
> Improve prompt generation speed

- Makefile.am
- arch/PKGBUILD.in
- homebrew/gitsh.rb.in
The package managers use the digest to verify the integrity of the tarball they've downloaded. 
Homebrew has deprecated SHA1, and we were using the same digest in both places, so upgrade both for simplicity.
> Use SHA256 for Homebrew and Arch package digests.

- Makefile.am
Trying to create a package for Archlinux I bumped into this error
```
cd ext/gitsh && make
make[1]: Entering directory '/home/cippaciong/.build/gitsh/src/gitsh-0.11/ext/gitsh'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/cippaciong/.build/gitsh/src/gitsh-0.11/ext/gitsh'
make[1]: Entering directory '/home/cippaciong/.build/gitsh/src/gitsh-0.11'
/usr/bin/mkdir -p '/home/cippaciong/.build/gitsh/pkg/gitsh//usr/bin'
/usr/bin/install -c gitsh '/home/cippaciong/.build/gitsh/pkg/gitsh//usr/bin'
mkdir -p "/usr/share/gitsh/ruby/lib/gitsh"
mkdir: cannot create directory ‘/usr/share/gitsh/ruby/lib’: Permission denied
make[1]: *** [Makefile:1336: install-data-local] Error 1
make[1]: Leaving directory '/home/cippaciong/.build/gitsh/src/gitsh-0.11'
make: *** [Makefile:1185: …
```
> Honor DESTDIR during make install

- homebrew/gitsh.rb.in
This causes Homebrew to set the appropriate LDFLAGS for Readline, which
is a keg only formula.
Without this, gitsh can't build against system Ruby (although it still
worked on systems where Homebrew's ruby formula was installed).
I couldn't find good documentation for the difference between `env=std`
and `env=superenv`, but this is where the necessary LDFLAGS value is set:
https://github.com/Homebrew/brew/blob/89fd34b/Library/Homebrew/build.rb#L100
> Homebrew: use env=std by default.

- INSTALL
- INSTALL.in
- configure.ac
- homebrew/gitsh.rb.in
On macOS systems, universal binaries contain multiple architectures, e.g.
the system Ruby is built for both i386 and x86_64. The Ruby `mkmf.rb` build
system will default to building universal C extensions when used with a
universal Ruby.
When installing gitsh via Homebrew, we build against the Homebrew version of
Readline. Until recently, this was a universal library (x86_64 & i386) but
is now x86_64 only [1].
It is possible to build against a universal Ruby and a non-universal
Readline, but only if the right flags are passed to the C extension's
`extconf.rb` script.
This commit:
- Adds support for a `$READLINE_ARCH` environment variable. When it is set,
the `configure` script will pass the right `--with-arch-flags` argument to
`extconf.rb`.
- Updates the Homebrew formula to set …
> Support explicit architectures for Readline.

- INSTALL
- INSTALL.in
- configure.ac
- homebrew/gitsh.rb.in
The OpenBSD port for Readline calls the library `ereadline`, which means that the gitsh configure script needed to be patched to be used on OpenBSD systems.
This commit introduces a `READLINE_LIB` environment variable, which can be used to specify an alternative name to be passed to the Ruby C-extension's configuration script.
Based on @mike-burns' patch to `configure` in the OpenBSD ports tree:
https://marc.info/?l=openbsd-ports&m=148340820830595&w=2
> Support alternative names for Readline.

- configure.ac
- Uses Autoconf's `$srcdir` instead of `basename $0` as the root of the source tree.
- Removes a redundant `cut`. This was intended to strip `./` from the beginnings of the resulting paths, but it wasn't portable (`./` wasn't prepended to the paths on some systems), and the way this list is generated and used has changed so much that it no longer appears to matter if the `./` is there at all.
Partly based on Mike Burns' patch to `configure` in the OpenBSD ports tree:
https://marc.info/?l=openbsd-ports&m=148340820830595&w=2
> Improve configure script's source file discovery.

- lib/gitsh/commands/internal_command.rb
- lib/gitsh/error.rb
- lib/gitsh/input_strategies/file.rb
- lib/gitsh/input_strategies/interactive.rb
- lib/gitsh/interpreter.rb
- spec/integration/error_handling_spec.rb
- spec/integration/running_scripts_spec.rb
- spec/support/scripts.rb
- spec/units/commands/internal/source_spec.rb
- spec/units/input_strategies/file_spec.rb
- spec/units/input_strategies/interactive_spec.rb
- spec/units/interpreter_spec.rb
When gitsh is invoked in a non-interactive manner, a parse error should result in a non-zero exit status.
To make sure this happens, parse error handling has been delegated to the input strategies by the interpreter. In an interactive session, we output an error message and continue the session. In a non-interactive session, we raise a `Gitsh::ParseError`, which will bubble up to the gitsh binary and
terminate the session with an exit status of 1.
Since the input strategy for files is used in a few internal places (in the interactive input strategy, for loading `.gitshrc`, and in the `:source` command), those call sites have been modified to handle the possibility of a `Gitsh::ParseError`.
> Non-zero exit status for bad scripts.

- lib/gitsh/commands/internal_command.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/magic_variables.rb
- man/man1/gitsh.1
- spec/integration/cd_command_spec.rb
- spec/integration/magic_variables_spec.rb
- spec/units/commands/internal/chdir_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/magic_variables_spec.rb
A couple of little helpers for finding a repository's root directory:
- A `$_root` magic variable which evaluates to the repository's root.
- An update to the `:cd` command, so that it changes to the repository root when invoked without a path. Thanks to @christoomey for suggesting this one in #242.
> Repo root helpers

- lib/gitsh/input_strategies/file.rb
- lib/gitsh/input_strategies/interactive.rb
- lib/gitsh/interpreter.rb
- lib/gitsh/lexer.rb
- lib/gitsh/parser.rb
- man/man1/gitsh.1
- spec/integration/error_handling_spec.rb
- spec/integration/multi_line_input_spec.rb
- spec/support/tokens.rb
- spec/units/input_strategies/file_spec.rb
- spec/units/input_strategies/interactive_spec.rb
- spec/units/interpreter_spec.rb
- spec/units/lexer_spec.rb
- spec/units/parser_spec.rb
Line breaks are supported in similar places to sh(1). Line breaks can be escaped anywhere by ending a line with a `\` character. Unescaped line breaks are also supported:
- after logical operators (`&&` and `||`),
- within strings,
- between commands wrapped in parentheses, and
- between commands in subshells.
The `Lexer` has been expanded to insert a `MISSING` token in all situations where the input is known to be incomplete (i.e. when the input ends with an escape character, or the input ends in any of the places where an unescaped line break can be used).
After invoking the `Lexer`, the `Interpreter` checks the token stream for `MISSING` tokens. If it finds any it requests another line of input from the current input strategy, appends it to the current input, and tries again.
A new …
> Support for multi-line commands.

- lib/gitsh/arguments/subshell.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/git_repository/status.rb
- spec/integration/arguments_spec.rb
- spec/integration/cd_command_spec.rb
- spec/integration/chaining_spec.rb
- spec/integration/comment_spec.rb
- spec/integration/correction_spec.rb
- spec/integration/create_repository_spec.rb
- spec/integration/default_command_spec.rb
- spec/integration/default_git_path_spec.rb
- spec/integration/error_handling_spec.rb
- spec/integration/escaping_spec.rb
- spec/integration/gitshrc_spec.rb
- spec/integration/greeting_spec.rb
- spec/integration/persistent_history_spec.rb
- spec/integration/source_command_spec.rb
- spec/integration/subshell_spec.rb
- spec/integration/variables_spec.rb
- spec/support/gitsh_runner.rb
- spec/units/commands/git_command_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/interpreter_spec.rb
This PR is broken down into the commits that quells the following
warnings:
- character class has duplicated range: /X/.
Where `/X/` is the regex.
- instance variable `@X` not initialized
Where `@X` is the instance variable.
- assigned but unused variable - X
Where `X` is the unused variable.
- ambiguous first argument; put parentheses or a space even after `/'
operator
- character class has duplicated range: /X/
Where `/X/` is the regex.
`\s+` matches the output `[\n\r\s]+` does.
I leave it up to the reviewer to pick and choose the warnings that feel
applicable to cherry-pick in, that is why they are broken out into
small and concise commits.
> Remove Ruby warnings

- lib/gitsh/interpreter.rb
- lib/gitsh/lexer.rb
- spec/units/interpreter_spec.rb
- spec/units/lexer_spec.rb
Prior to this commit, an incomplete variable reference (a line ending with
an unescaped `$` character, or unclosed `${`) would produce a lexing error.
After this commit it produces a parse error instead.
We want to start using the lexer for understanding tab completion context,
which means we need to lex incomplete input. Having all legal-but-incomplete
input cause parse errors instead of lexing errors will make this much
easier.
Note that it's still possible to produce lexing errors with invalid input,
but it's more reasonable for the tab completion system to just ignore that
and not provide any completions.
A new `EXPECTED` token type was used instead of the existing `MISSING` token
type, because `MISSING` is used to determine that the user can enter another
line to complete the …
> Improve variable lexing.

- lib/gitsh/environment.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/magic_variables.rb
- lib/gitsh/tab_completion/README.md
- lib/gitsh/tab_completion/context.rb
- lib/gitsh/tab_completion/facade.rb
- lib/gitsh/tab_completion/variable_completer.rb
- spec/integration/tab_completion_spec.rb
- spec/units/environment_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/magic_variables_spec.rb
- spec/units/tab_completion/context_spec.rb
- spec/units/tab_completion/facade_spec.rb
- spec/units/tab_completion/variable_completer_spec.rb
This commit introduces a `Gitsh::TabCompletion::VariableCompleter` object. This is completely separate from the NFA-based completion we use for most things, because:
- we immediately know we need to use variable completion based on lexical analysis of the input without having to walk through the NFA's states, and
- the context in which the variable appears doesn't inform the completions we present the user with.
The `Gitsh::TabCompletion::Facade` object gains the responsibility of deciding which type of completion to invoke, based on information from the `Gitsh::TabCompletion::Context` object.
> Support tab completion for variables.

- .hound.yml
- .rubocop.yml
Configure Rubocop to enforce single quotes, if there is no need for
interpolation and therefore double quotes.
> Enable hound

- spec/units/tab_completion/automaton_spec.rb
- spec/units/tab_completion/matchers/command_matcher_spec.rb
- spec/units/tab_completion/matchers/path_matcher_spec.rb
- spec/units/tab_completion/matchers/remote_matcher_spec.rb
- spec/units/tab_completion/matchers/revision_matcher_spec.rb
This commit quells warnings along the likes of:
```
warning: assigned but unused variable - X
```
Where X is the variable in question.
> Quell ruby warnings for unused variables

- etc/completions
- lib/gitsh/tab_completion/automaton.rb
- lib/gitsh/tab_completion/dsl/lexer.rb
- lib/gitsh/tab_completion/dsl/maybe_operation_factory.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/dsl/star_operation_factory.rb
- man/man5/gitsh_completions.5.in
- spec/units/tab_completion/automaton_spec.rb
- spec/units/tab_completion/dsl/lexer_spec.rb
- spec/units/tab_completion/dsl/maybe_operation_factory_spec.rb
- spec/units/tab_completion/dsl/parser_spec.rb
- spec/units/tab_completion/dsl/star_operation_factory_spec.rb
This PR adds support for the `*` operator (zero or more times), and the `?` operator (zero or one times) to the gitsh tab completion DSL.
It also adds filtering for duplicate options, otherwise the more complex graphs enabled by the DSL changes can cause problems with path completion (see commit message for more details).
---
In order to motivate this change with a failing test, this PR starts by updating the tab completion configuration file to read:
$command ($revision|$path|$remote)* --? $path+
The resulting NFA state graph looks like this:
> Add * and ? operators to git_completions(5)

- etc/completions
- lib/gitsh/tab_completion/dsl/lexer.rb
- lib/gitsh/tab_completion/dsl/null_factory.rb
- lib/gitsh/tab_completion/dsl/option_transition_factory.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/dsl/rule_factory.rb
- lib/gitsh/tab_completion/matchers/unknown_option_matcher.rb
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/units/tab_completion/dsl/lexer_spec.rb
- spec/units/tab_completion/dsl/option_transition_factory_spec.rb
- spec/units/tab_completion/dsl/parser_spec.rb
- spec/units/tab_completion/dsl/rule_factory_spec.rb
- spec/units/tab_completion/matchers/unknown_option_matcher_spec.rb
This PR further expands the tab completion DSL with the ability to define options like `-f` or `--force`.
- Rules can contain an `$opt` variable, which indicates where options may appear. This will match on anything beginning with `-` or `--`, and complete to any known options.
- Rules can list known options, and the arguments expected by those options.
The config file in the repo is still pretty simple, but after this PR rules like this become possible:
```
commit $opt* --? $path+
--all
--fixup $revision
--file $path
--untracked-files (no|normal|all)?
```
Producing this state graph:
---
Visualisation of `etc/completions` after this PR:
> Tab completion DSL: Options support

- etc/completions
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/matchers/anything_matcher.rb
- man/man5/gitsh_completions.5.in
- spec/units/tab_completion/dsl/parser_spec.rb
- spec/units/tab_completion/matchers/anything_matcher_spec.rb
This tab completion configuration file includes:
- All Git commands without arguments.
- Popular Git commands, with their options and arguments.
- Internal gitsh commands, with their options and arguments.
The resulting state graph has 575 nodes and 1,627 edges, and is too large for the visualisation tool to produce anything very useful.
There are some argument types that we can't currently complete, and others that are unlikely to ever be practical to complete. To represent those this commit also introduces a `$anything` variable to the tab completion DSL. The variable's corresponding `AnythingMatcher` class will match any input, but produce no completions.
> Tab completions DSL: configuration file

- lib/gitsh/prompter.rb
- man/man1/gitsh.1.in
- spec/units/prompter_spec.rb
See #323 
This required a fairly minimal change to the pattern-matching substitution when generating the prompt string. I also updated the relevant section of the man page.
The tests fail without my code and pass with it, though it should be noted that this was my first experience with ruby and spec.
> Implement git_command placeholder in prompt

- lib/gitsh/tab_completion/automaton_factory.rb
- man/man1/gitsh.1.in
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/support/file_system.rb
- spec/units/tab_completion/automaton_factory_spec.rb
This PR adds support for a `$HOME/.gitsh_completions` file, so that users can add tab completion rules for their custom Git commands and aliases.
Resolves #315
> Custom completions file

- lib/gitsh/git_command_list.rb
- lib/gitsh/git_repository.rb
- spec/units/git_command_list_spec.rb
- spec/units/git_repository_spec.rb
This PR changes how gitsh builds a full list of available commands for tab
completion.
This list was originally built by parsing the output of `git help -a`, which
was based on the approach taken by the tab completion scripts distributed
with Git for various general-purpose shells.
In Git version 2.20, the output of `git help -a` changed in ways that
weren't compatible with our existing parsing code. Passing `--no-verbose`
continues to provide the old output format. Meanwhile, a new `--list-cmds`
argument was added, which outputs commands as a simple list, but is also
described in the git(1) manual page as being experimental and subject to
change.
To make sure we continue supporting a range of Git versions, and we won't
have major problems if the `--list-cmds` argument is removed, this PR …
> Git 2 20 tab complete

- lib/gitsh/tab_completion/context.rb
- spec/units/tab_completion/context_spec.rb
When there is no input, hitting tab twice should complete a list of all available commands.
There was a bug in the `Gitsh::TabCompletion::Context#completing_variable?` method which caused a crash in this case, because it would try to read the type of the last token, which was `nil`.
> Fix tab completion with no input.

- ext/gitsh/src/line_editor.c
- man/man1/gitsh.1.in
- spec/integration/inputrc_spec.rb
Fixes #294.
This change allows users to set conditional rules in their `.inputrc` that only apply to gitsh.
See: http://web.mit.edu/gnu/doc/html/rlman_1.html#SEC10
> Set `rl_readline_name` to "gitsh"

- .rubocop.yml
- lib/gitsh/tab_completion/alias_expander.rb
- lib/gitsh/tab_completion/context.rb
- lib/gitsh/tab_completion/facade.rb
- lib/gitsh/tab_completion/tokens_to_words.rb
- man/man1/gitsh.1.in
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/units/tab_completion/alias_expander_spec.rb
- spec/units/tab_completion/facade_spec.rb
- spec/units/tab_completion/tokens_to_words_spec.rb
Fixes #340.
When a user attempts to tab complete the arguments of an alias, they would previously (since v0.13) need a custom tab completion rule. This commit expands the alias behind the scenes, so that the tab completion system is using all available context, e.g. with `alias.a = add` the tab completion system will treat `a foo<TAB>` as if it were `add foo<TAB>`, allowing the standard tab completion rules for `add` to be used without any additional configuration. This also applied to more complex aliases, e.g. `alias.rmbranch = branch -d` would allow for `rmbranch <TAB>` to complete revision names.
A potential downside here is that it's no longer possible to define a custom tab completion rule for Git command aliases, which could be annoying in some situations. It seems like getting …
> Expand aliases

- etc/completions
- lib/gitsh/environment.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/matchers/branch_matcher.rb
- lib/gitsh/tab_completion/matchers/revision_matcher.rb
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/units/environment_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/tab_completion/matchers/branch_matchers_spec.rb
Fixes #352
The tab completion DSL had a `$revision` variable which produces branch names, tag names, etc. In some contexts it's too general, e.g. `branch -D` accepts a branch name but not a tag. In those contexts we were using `$anything` to avoid producing invalid tab completion options.
This PR introduces a more specific `$branch` variable that can be used when we want to only tab complete branch names.
> Add a $branch variable to tab completion

- etc/completions
- lib/gitsh/tab_completion/README.md
- lib/gitsh/tab_completion/automaton.rb
- lib/gitsh/tab_completion/dsl/fallback_transition_factory.rb
- lib/gitsh/tab_completion/dsl/lexer.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/units/tab_completion/automaton_spec.rb
- spec/units/tab_completion/dsl/fallback_transition_factory_spec.rb
- spec/units/tab_completion/dsl/lexer_spec.rb
- spec/units/tab_completion/dsl/parser_spec.rb
Fixes #317.
This PR adds fallback rules to the default tab completion configuration, which will only be used when no other rule applies. These provide sensible defaults for things that aren't covered by a specific rule, e.g. non-Git commands like `!rm`, or custom Git commands that have not been configured.
Providing generic fallbacks wasn't possible without adding some new features to the tab completion DSL.
To illustrate why the existing DSL was insufficient, consider the following rules:
```
add $path+
$command ($path|$revision|$remote)+
```
A user trying to tab complete arguments to git-add(1) will match both rules: the input will match the `add` rule, and the user will correctly be offered paths to complete, but it will also match the `$command` rule, and so they will also be offered …
> Tab completion fallbacks

- etc/completions
- lib/gitsh/environment.rb
- lib/gitsh/git_repository.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/matchers/tag_matcher.rb
- man/man5/gitsh_completions.5.in
- spec/integration/tab_completion_spec.rb
- spec/units/environment_spec.rb
- spec/units/git_repository_spec.rb
- spec/units/tab_completion/matchers/tag_matchers_spec.rb
The `$tag` matchers produces tag names, and can be used in places where the `$revision` matcher is too permissive, e.g. `tag -d` only accepts a tag name, not a branch name etc.
Checks off one of the items in #314
> Introduce $tag matcher for tab completion.

- lib/gitsh/tab_completion/dsl/parser.rb
- spec/units/tab_completion/dsl/parser_spec.rb
If the file is empty, or contains only comments, it should be interpreted as "no rules". Previously it caused a parse error and would crash.
Ticks off one of the items in #316
> Handle empty tab completion config files

- lib/gitsh/tab_completion/dsl/parser.rb
- man/man5/gitsh_completions.5.in
- spec/units/tab_completion/dsl/parser_spec.rb
Before this commit, the following tab completion rule was considered valid, but would cause an infinite loop when used:
add $opt
--example $opt
This was also considered valid, but doesn't really make sense:
add $opt
--example --nested
This commit resolved the situation by modifying the parser to not accept the `$opt` token or another option token (e.g. `--nested`) in the definition of an option.
Unfortunately this complicates the parser somewhat, because the tokens permitted in a rule and in an option definition have diverged.
Checks off the final item in #316
> Prevent invalid option definitions.

- lib/gitsh/tab_completion/dsl.rb
- lib/gitsh/tab_completion/dsl/parse_error.rb
- lib/gitsh/tab_completion/dsl/parser.rb
- lib/gitsh/tab_completion/facade.rb
- spec/integration/completion_errors_spec.rb
- spec/support/gitsh_runner.rb
- spec/units/input_strategies/interactive_spec.rb
- spec/units/tab_completion/dsl/parse_error_spec.rb
- spec/units/tab_completion/dsl/parser_spec.rb
- spec/units/tab_completion/facade_spec.rb
This PR adds error reporting for problems with the tab completion. It covers several of the issues raised in #316.
Specifically:
- Load the completion files on start up, so that errors happen immediately and not when the user first tries to use completion.
- Output useful errors when the file fails to parse (i.e. valid tokens in an invalid order, like `??`).
- Output useful errors when the file contains an invalid variable (e.g. `$foo`)
> Completion config file error handling

- lib/gitsh/capturing_environment.rb
- lib/gitsh/lexer.rb
- lib/gitsh/parser.rb
- spec/integration/subshell_spec.rb
- spec/units/capturing_environment_spec.rb
- spec/units/lexer_spec.rb
This PR fixes two related bugs with subshells:
1. Using the `:echo` command in a subshell would be output to standard output, instead of being captured by the subshell. This was because the `CapturingEnvironment` would override the `Environment#output_stream` method, but not the convenience `#puts` and `#print` methods.
2. The space between a subshell argument and the next argument was lost. This was because the lexer considered any space following a `)` character to be part of the `RIGHT_PAREN` or `SUBSHELL_END` token. For `RIGHT_PAREN` that's fine; for `SUBSHELL_END` it isn't.
Fixes #328.
> Fix subshell bugs

- etc/completions
This commit updates the default tab completion configuration to handle things like `git show mas<tab>`
(Probably doesn't need review, just opening a PR to set CI run)
> git-show(1) takes one or more revisions.

- .travis.yml
- Makefile.am
- configure.ac
- configure.rb
- src/gitsh.c
- src/gitsh.rb.in
Fixes #41.
This resolves the process name issue by running a Ruby interpreter in-process instead of via `ruby(1)`. The implementation is inspired by the article [Running Ruby in C](https://silverhammermba.github.io/emberb/embed/) and [Ruby's own `main` function](https://github.com/ruby/ruby/blob/bdbc8a8f1214b601ca409f66f2fe00ac06f2e99a/main.c). Instead of invoking `ruby(1)` as a subprocess, we use `ruby.h` and `libruby` to perform the same function directly.
In order to test this, I hard-coded the paths to `ruby.h`, `ruby/config.h` and `libruby` on my machine. The full set of compiler flags, including the platform-specific location of `ruby/config.h`, are available via `pkg-config(1)`. I'm not very familiar with Autotools, so I could use some help figuring out how to correctly include …
> Change process name to gitsh by embedding Ruby in C

- lib/gitsh/tab_completion/matchers/path_matcher.rb
- spec/units/tab_completion/matchers/path_matcher_spec.rb
When tab completing a path argument without entering the beginning of the
path we expect the completion options to be the files in the current
directory.
Prior to this commit the only option would be `/`, until the user entered at
least the first letter of the path to be completed.
Fixes #362
> Fix tab completing paths with no prefix.

- etc/completions
`git reset` without specifying a revision defaults to using `HEAD`.
I guessed at the syntax based on the examples nearby.
> Revision argument to git-reset is optional

- README.md
I wasn't entirely sure where to view all the documentation for `gitsh`
when I first started using it. I soon found the man page, but wanted to
make it more obvious for anyone just starting out.
> Add note about `man gitsh` to Readme.
